# Copyright (C) 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//protos/services_v2:ts_proto.bzl", "ts_proto_library")

package(default_visibility = ["//visibility:public"])

ts_proto_library(
    name = "operations_ts_proto",
    has_grpc = False,
    proto = "@googleapis//google/longrunning:operations_proto",
    deps = [
        "@googleapis//google/rpc:status_proto",
        "@protobuf//:any_proto",
        "@protobuf//:duration_proto",
        "@protobuf//:empty_proto",
    ],
)
